# Default values for router-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: kwetter-data-service

# .NET environment
environment: Development

resources:
  memory: 500m
  cpu: 250m
# Configuration for Yugabyte connection
yugabyte:
  host: ""
  user: ""
  password: ""
  useYugabyte: "false"

# Service bus config
rabbitmq:
  host: rabbitmq
  port: "5672"
  user: rabbit
  password: rabbit
  virtualHost: /