# .NET environment
environment: Development

# Service bus config
rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  virtualHost: /

mongo:
  collection: saga
  database: kweeter