# .NET environment
environment: Development

# Configuration for Yugabyte connection
yugabyte:
  host: ""
  user: ""
  password: ""

# Service bus config
rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  queue: py-router
  virtualHost: /

mongo:
  collection: saga
  database: kweeter