# Default values for router-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: kweeter

# .NET environment
environment: Development

resources:
  memory: 500m
  cpu: 250m
# Service bus config
rabbitmq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
  virtualHost: /

mongo:
  collection: saga
  database: kweeter