# .NET environment
environment: Development

resources:
  memory: 500m
  cpu: 250m
serviceName: content-service

# Configuration for Yugabyte connection
yugabyte:
  host: ""
  user: ""
  password: ""
  useYugabyte: "false"

# Service bus config
rabbitmq:
  host: rabbitmq