apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{ .Values.serviceName }}-db
  name: {{ .Values.serviceName }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
