apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
    - name: "443"
      port: 443
      targetPort: 443
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: {{ .Release.Name }}
