apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: {{ .Release.Name }}
    spec:
      containers:
        - image: fontyssa/kwetter
          name: {{ .Release.Name }}
          ports:
            - containerPort: 443
            - containerPort: 80
          resources: {}
      restartPolicy: Always
