apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Values.serviceName }}-db
  name: {{ .Values.serviceName }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.serviceName }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.28.0 (c4137012e)
      labels:
        org: routing-system
        class: {{ .Values.serviceName }}-db
        app.kubernetes.io/name: {{ .Values.serviceName }}-db
        io.kompose.service: {{ .Values.serviceName }}-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.serviceName }}
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: fontyssa/postgres-extended
          name: {{ .Values.serviceName }}-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.serviceName }}-db
      restartPolicy: Always
      volumes:
        - name: {{ .Values.serviceName }}-db
          persistentVolumeClaim:
            claimName: {{ .Values.serviceName }}-db
