# Default values for router-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: kwetter-api

# .NET environment
environment: Development

resources:
  memory: 500m
  cpu: 250m
# Service bus config
rabbitmq:
  host: rabbitmq
  port: "5672"
  user: rabbit
  password: rabbit
  virtualHost: /

cacheUri: http://cache-service/

# Keycloak config for authentication
keycloak:
  authServerUrl: http://keycloak:8080/
  realm: Kwetter
  resource: test-client
  credentials:
    secret: ""
  confidentialPort: "0"
  sslRequired: "none"
  verifyTokenAudience: "true"
  rolesSource: Realm