apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.serviceName }}
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:

        io.kompose.service: {{ .Values.serviceName }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: CACHE_URI
              value: {{ .Values.cacheUri }}
            - name: Keycloak__RolesSource
              value: {{ .Values.keycloak.rolesSource }}
            - name: Keycloak__auth-server-url
              value: {{ .Values.keycloak.authServerUrl }}
            - name: Keycloak__confidential-port
              value: {{ .Values.keycloak.confidentialPort | quote}}
            - name: Keycloak__credentials__secret
              valueFrom:
                secretKeyRef:
                  key: secret
                  name: {{ .Values.serviceName }}-keycloak
            - name: Keycloak__realm
              value: {{ .Values.keycloak.realm }}
            - name: Keycloak__resource
              value: {{ .Values.keycloak.resource }}
            - name: Keycloak__ssl-required
              value: {{ .Values.keycloak.sslRequired | quote  }}
            - name: Keycloak__verify-token-audience
              value: {{ .Values.keycloak.verifyTokenAudience | quote }}
            - name: RABBITMQ_HOST
              value: {{.Values.rabbitmq.host}}
            - name: RABBITMQ_PORT
              value: {{.Values.rabbitmq.port | quote}}
            - name: RABBITMQ_USERNAME
              value: {{.Values.rabbitmq.user}}
            - name: RABBITMQ_PASSWORD
              value: {{.Values.rabbitmq.password}}
            - name: RABBITMQ_VIRTUAL_HOST
              value: {{.Values.rabbitmq.virtualHost}}
          image: fontyssa/kwetter-api
          name: {{ .Values.serviceName }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{.Values.resources.memory | quote }}
              cpu: {{.Values.resources.cpu | quote }}
      restartPolicy: Always
