apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:

        io.kompose.service: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: MONGO_CONNECTION
              value: mongodb://{{ .Release.Name }}-mongo:27017
            - name: MONGO_DATABASE
              value: {{ .Values.mongo.database }}
            - name: MONGO_COLLECTION
              value: {{ .Values.mongo.collection }}
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: REDIS_CONFIG
              value: {{ .Release.Name }}-redis
            - name: REDIS_INSTANCE
              value: {{ .Values.redis.instance }}
          image: fontyssa/kwetter-cache-service
          name: {{ .Release.Name }}
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
