apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}-mongo
  name: {{ .Release.Name }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:

        io.kompose.service: {{ .Release.Name }}-mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo }}
          image: mongo
          name: {{ .Release.Name }}-mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: {{ .Release.Name }}-volume
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-volume
