apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: {{ .Values.serviceName }}

