apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.serviceName }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:

        io.kompose.service: {{ .Values.serviceName }}
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.environment }}
            - name: MONGO_CONNECTION
              value: mongodb://{{ .Values.serviceName }}-mongo:27017
            - name: MONGO_DATABASE
              value: {{ .Values.mongo.database }}
            - name: MONGO_COLLECTION
              value: {{ .Values.mongo.collection }}
            - name: RABBITMQ_HOST
              value: {{.Values.rabbitmq.host}}
            - name: RABBITMQ_PORT
              value: {{.Values.rabbitmq.port | quote}}
            - name: RABBITMQ_USERNAME
              value: {{.Values.rabbitmq.user}}
            - name: RABBITMQ_PASSWORD
              value: {{.Values.rabbitmq.password}}
            - name: RABBITMQ_VIRTUAL_HOST
              value: {{.Values.rabbitmq.virtualHost}}
            - name: REDIS_CONFIG
              value: {{ .Values.serviceName }}-redis
            - name: REDIS_INSTANCE
              value: {{ .Values.redis.instance }}
          image: fontyssa/kwetter-cache-service
          name: {{ .Values.serviceName }}
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
