apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}-mongo
  name: {{ .Release.Name }}-mongo
spec:
  ports:
    - name: "3301"
      port: 3301
      targetPort: 27017
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: {{ .Release.Name }}-mongo

