apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: {{ .Release.Name }}-redis
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Release.Name }}-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose-cloud.yml -o kweeter
        kompose.version: 1.28.0 (c4137012e)
      labels:

        io.kompose.service: {{ .Release.Name }}-redis
    spec:
      containers:
        - image: redis:7-alpine
          name: {{ .Release.Name }}-redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
