apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-yugabyte
data:
  host: {{ .Values.yugabyte.host| b64enc }}
  username: {{ .Values.yugabyte.user| b64enc }}
  password: {{ .Values.yugabyte.password | b64enc }}